dropbox:
    access_token: 'your_dropbox_api_access_token'

sleepcycle:
    email: 'your_sleepcycle@email.com'
    password: 'your_sleep_secure_password'

toggl:
    email: 'your_toggl_email@email.com'
    api_token: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
    workspace_id: 'xxxxxx'
