---
title: Time used as a student
author: Jakob Gerhard Martinussen
date: April 14th, 2016
output:
  html_document:
    theme: sandstone
    df_print: paged
    code_folding: hide
    css: knitr.css
---

```{r, echo = FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(error = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(results = "hold")
knitr::opts_chunk$set(fig.fullwidth = TRUE)
knitr::opts_chunk$set(fig.width = 10)
```

# Packages used

```{r}
library(tidyverse)
library(tidyjson)
library(magrittr)

# For use of `ymd_hms`
library(lubridate)
```


# Importing the data

Start by importing the data

```{r, cache = TRUE}
toggl_json <- read_json(path = "../data/toggl/tidy_details.json")
toggl <- toggl_json %>%
  as.tbl_json() %>%
  gather_array() %>%
  spread_values(
    description = jstring("description"),
    start = jstring("start"),
    end = jstring("end"),
    study_session_duration = jnumber("dur"),
    project = jstring("project")
  ) %>%
  mutate(
    date = as.POSIXct(start),
    start = ymd_hms(start),
    end = ymd_hms(end),
    study_session_duration = study_session_duration / (1000 * 60 * 60)
  ) %>%
  rename(course = "project") %>%
  dplyr::filter(study_session_duration < 12) %>%
  select(-document.id, -array.index)
```

```{r, echo = FALSE}
toggl$description %<>%
  str_replace_all(c(
    ".*[Øø]v.*" = "Exercise",
    ".*[Ff]orelesning.*" = "Lecture",
    ".*[Tt]eori.*" = "Theory",
    ".*Eksamen.*" = "Exam",
    ".*Euler.*" = "Exercise",
    ".*Det tenkende.*" = "Theory",
    ".*Ethics.*" = "Theory",
    ".*Nedlasting.*" = "Organization",
    ".*Innlevering.*" = "Hand-in",
    ".*Lab.*" = "Hand-in",
    ".*Seminar.*" = "Lecture",
    ".*Pedag.*" = "Pedagogics",
    ".*Lære bort.*" = "Pedagogics",
    ".*Maple.*" = "Hand-in",
    ".*Theory.*" = "Theory",
    "Mattelab" = "Hand-in",
    ".*[Ll]ese.*" = "Theory",
    ".*Wunderlist.*" = "Organization",
    ".*[Kk]apittel.*" = "Theory",
    ".*[Rr]epetisjon.*" = "Repetition",
    "Inn" = "Hand-in",
    "Intervju" = "Exercise",
    "Google Calendar" = "Organization",
    "Kok" = "Hand-in",
    ".*[Oo]rganiser.*" = "Organization",
    "Anbefalte oppgaver" = "Exercise"
  ))
toggl$description[toggl$description == ""] <- "Hand-in"
```

```{r}
grades <- tibble(
  course = toggl %>%
    select(course) %>%
    unique() %>%
    arrange(course) %>%
    unlist(),
  course_code = c(
    "EXPH0004", "Org", "TDT4102", "TDT4105", "TDT4120", "TDT4136", "TDT4145",
    "TEP4105", "TFY4145", "TFY4155", "TFY4165", "TFY4215", "TIØ4146",
    "TIØ4258", "TMA4100", "TMA4105", "TMA4115", "TMA4120", "TMA4145",
    "TMA4150", "TMA4180", "TMA4195", "TMA4212", "TMA4215", "TMA4245",
    "TMA4265", "TMA4267", "TMA4268", "TMA4295", "TMA4300", "TMA4315",
    "TMA4320", "TMA4850", "TMT4110"
  ),
  grade = as.ordered(c(
    "A", NA, "A", "A", "A", NA, NA, "B", "A", "A", "B", NA, "A", "B", "A", "A",
    "A", "B", "C", NA, "C", "C", "C", "C", "A", "D", "B", NA, NA, NA, "A", "B",
    NA, "B"
  )),
  semester = c(
    1, NA, 4, 1, 5, 7, 10, 3, 1, 2, 3, 10, 9, 3, 1, 2, 2,
    3, 5, 6, 6, 9, 6, 9, 4, 5, 6, 10, 5, 10, 9, 4, 10, 2
  )
)
```

```{r, fig.width = 18, fig.height = 8}
theme_set(theme_minimal() + theme(legend.position = "bottom"))
colors <- list(
  green = "#536D3D",
  light_green = "#9AB73C",
  orange = "#E5D017",
  dark_orange = "#E59E15",
  red = "#DB4801"
)

courses <- toggl %>%
  group_by(course) %>%
  summarize(study_hours = sum(study_session_duration)) %>%
  inner_join(grades)

courses %>%
  ggplot() +
  aes(x = reorder(course, -study_hours), y = study_hours) +
  geom_bar(stat = "identity", aes(fill = grade)) +
  coord_flip() +
  theme(legend.position = "bottom") +
  scale_fill_manual(
    values = as.vector(unlist(colors)),
    na.value="gray"
  ) +
  ylab("Time spent  [hours]") +
  xlab("") +
  theme(
    panel.grid.major.y = element_blank(),
    panel.grid.minor.y = element_blank()
  )
```

```{r}
courses %>%
  ggplot() +
  aes(x = reorder(course_code, semester), y = study_hours) +
  geom_bar(stat = "identity", aes(fill = grade)) +
  geom_vline(xintercept = 4.5, color = colors$red) +
  geom_vline(xintercept = 8.5, color = colors$red) +
  geom_vline(xintercept = 12.5, color = colors$red) +
  geom_vline(xintercept = 15.5, color = colors$red) +
  geom_vline(xintercept = 18.5, color = colors$red) +
  geom_vline(xintercept = 23.5, color = colors$red) +
  geom_vline(xintercept = 24.5, color = colors$red) +
  geom_vline(xintercept = 28.5, color = colors$red) +
  theme(legend.position = "bottom") +
  scale_fill_manual(
    values = as.vector(unlist(colors)),
    na.value="gray"
  ) +
  xlab("") +
  ylab("Time spent  [hours]") +
  theme(axis.text.x = element_text(angle = 90))
```

```{r}
# For `rollmean`
library(zoo)

days <- toggl %>%
  group_by(date) %>%
  summarize(study_hours = sum(study_session_duration)) %>%
  add_column(rolling_mean = rollmean(.$study_hours, 30, na.pad=TRUE))

days %>%
  ggplot() +
  aes(x = date, y = study_hours) +
  geom_point(aes(color = study_hours)) +
  geom_line(aes(y = rolling_mean), color = "blue", alpha = 0.3) +
  geom_smooth()
```

```{r}
# For use of `percent_format()`
library(scales)

binwidth <- 0.5
days %>%
  ggplot() +
  aes(x = study_hours, binwidth * ..density..) +
  geom_histogram(
    aes(fill = ..density..),
    binwidth = binwidth,
    color = "white"
  ) +
  geom_vline(
    aes(xintercept = mean(days$study_hours), color = "Mean"),
    size = 3
  ) +
  scale_y_continuous(labels = percent_format()) +
  scale_x_continuous(breaks = 0:12)
```

```{r}
library(RColorBrewer)
toggl %>%
  group_by(course, description) %>%
  summarize(time = sum(study_session_duration)) %>%
  ungroup() %>%
  right_join(grades) %>%
  filter(!is.na(grade)) %>%
  group_by(grade, description) %>%
  summarize(time = sum(time)) %>%
  ggplot() +
  aes(x = grade, y = time, fill = description) +
  geom_bar(stat = "identity") +
  scale_fill_brewer(palette = "Spectral")
```



```{r, cache = TRUE}
# For use of `str_extract`
library(stringr)

sleep_json <- read_json(path = "../data/sleep_sessions.json")
sleep <- sleep_json %>%
  as.tbl_json() %>%
  enter_object("sleep_sessions") %>%
  gather_keys() %>%
  spread_values(
    start_date = jstring("start_local"),
    stop_date = jstring("stop_local"),
    date = jstring("stop_local"),
    start = jstring("start_local"),
    stop = jstring("stop_local"),
    wakeup_mood = jnumber("rating"),
    heartrate = jstring("heartrate"),
    sleep_quality = jnumber("stats_sq"),
    sleep_duration = jnumber("stats_duration"),
    steps = jstring("steps"),
    sleep_notes = jstring("sleep_notes")
  ) %>%
  mutate(
    heartrate = str_extract(heartrate, "\\d+") %>% as.numeric(),
    steps = str_extract(steps, "\\d+") %>% as.numeric(),
    date = as.POSIXct(date),
    start_date = as.POSIXct(start_date),
    stop_date = as.POSIXct(stop_date),
    start = ymd_hms(start),
    stop = ymd_hms(stop),
    sleep_duration = sleep_duration / (60 * 60)
  ) %>%
  select(-document.id, -key) %>%
  add_column(source = "iOS")
```

```{r}
sleep_notes <- sleep$sleep_notes %>%
  str_split(pattern = ", ")

note_categories <- sleep_notes %>%
  unlist() %>%
  unique() %>%
  extract(-1)

for (note_category in note_categories) {
  if (note_category %in% colnames(sleep)) break

  boolean_vector <- vector()
  for (sleep_note in sleep_notes) {
    has_note <- note_category %in% sleep_note
    boolean_vector <- c(boolean_vector, has_note)
  }

  sleep[[note_category]] <- boolean_vector
}
```

```{r}
android_json <- read_json(path = "../data/sleep/android.json")
android <- android_json %>%
  as.tbl_json() %>%
  gather_array() %>%
  spread_values(
    start = jstring("from"),
    stop = jstring("to"),
    sleep_duration = jnumber("hours")
  ) %>%
  mutate(
    start = dmy_hm(start),
    stop = dmy_hm(stop)
  ) %>%
  mutate(
    date = as.POSIXct(start),
    start_date = as.POSIXct(start),
    stop_date = as.POSIXct(stop)
  ) %>%
  add_column(source = "Android") %>%
  select(-document.id, -array.index)

if (!("Android" %in% sleep$source)) {
  sleep %<>% bind_rows(android)
}
```

```{r}
days %<>% full_join(sleep)
```

```{r}
model <- lm(study_hours ~ sleep_duration, data = days)
days %>%
  filter(sleep_duration > 5) %>%
  ggplot() +
  aes(x = sleep_duration, y = study_hours) +
  geom_point() +
  stat_smooth(method = "lm")
```

```{r}
toggl %>%
  group_by(description) %>%
  summarize(study_hours = sum(study_session_duration)) %>%
  ggplot() +
  aes(x = reorder(description, study_hours), y = study_hours) +
  geom_bar(stat = "identity", aes(fill = study_hours)) +
  coord_flip()
```

```{r, cols.print = 30}
days %>% drop_na()
```

```{r, fig.fullwidth = TRUE, fig.width = 20, fig.height = 5}
time_of_day <- trans_new(
  "time_of_day",
  transform = function(x) {(x - 18) %% 24},
  inverse = function(x) {(x + 18) %% 24},
  breaks = function(x) {1:24}
)

sleep %>%
  mutate(
    in_bed = ((hour(start) + minute(start) / 60)),
    out_of_bed = ((hour(stop) + minute(stop) / 60))
  ) %>%
  ggplot() +
  aes(x = stop_date) +
  geom_segment(
    aes(
      x = stop_date,
      xend = stop_date,
      y = in_bed,
      yend = out_of_bed,
      color = sleep_duration
    )
  ) +
  geom_smooth(
    aes(y = in_bed, linetype = "Going to bed"),
    fill = "#E59E15",
    color = "#77AB43",
    alpha = 0.3
  ) +
  geom_smooth(
    aes(y = out_of_bed, linetype = "Out of bed"),
    fill = "#E59E15",
    color = "#77AB43",
    alpha = 0.3
  ) +
  scale_y_continuous(
    name = "Time of day",
    trans = time_of_day
  ) +
  scale_linetype_manual(
    values = c("dotted", "dashed"),
    name = "Sleep trend",
    labels = c("Going to bed", "Waking up")
  ) +
  theme(legend.position = "bottom") +
  theme_minimal()
```

```{r, fig.width = 16, fig.height = 9}
sleep %>%
  mutate(rolling_mean = rollmean(sleep_duration, 30, na.pad = TRUE)) %>%
  filter(sleep_duration > 4) %>%
  ggplot() +
  aes(x = date, y = sleep_duration) +
  geom_point(aes(color = sleep_duration), alpha = 0.5) +
  geom_smooth(size = 3) +
  geom_line(aes(y = rolling_mean)) +
  scale_y_continuous(breaks = 1:15)
```


<style>
img {
    max-width: 100vw;
    position: relative;
    left: 50%;
    -moz-transform: translateX(-50%);
    -webkit-transform: translateX(-50%);
    transform: translateX(-50%);
}
</style>
